/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as LabRunIdRouteImport } from './routes/lab.$runId'
import { Route as GenomeRunIdRouteImport } from './routes/genome.$runId'
import { Route as DigitalTwinRunIdRouteImport } from './routes/digital-twin.$runId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRunIdRoute = LabRunIdRouteImport.update({
  id: '/lab/$runId',
  path: '/lab/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenomeRunIdRoute = GenomeRunIdRouteImport.update({
  id: '/genome/$runId',
  path: '/genome/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRunIdRoute = DigitalTwinRunIdRouteImport.update({
  id: '/digital-twin/$runId',
  path: '/digital-twin/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/digital-twin/$runId': typeof DigitalTwinRunIdRoute
  '/genome/$runId': typeof GenomeRunIdRoute
  '/lab/$runId': typeof LabRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/digital-twin/$runId': typeof DigitalTwinRunIdRoute
  '/genome/$runId': typeof GenomeRunIdRoute
  '/lab/$runId': typeof LabRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/digital-twin/$runId': typeof DigitalTwinRunIdRoute
  '/genome/$runId': typeof GenomeRunIdRoute
  '/lab/$runId': typeof LabRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/digital-twin/$runId'
    | '/genome/$runId'
    | '/lab/$runId'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/digital-twin/$runId'
    | '/genome/$runId'
    | '/lab/$runId'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/digital-twin/$runId'
    | '/genome/$runId'
    | '/lab/$runId'
    | '/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  DigitalTwinRunIdRoute: typeof DigitalTwinRunIdRoute
  GenomeRunIdRoute: typeof GenomeRunIdRoute
  LabRunIdRoute: typeof LabRunIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$runId': {
      id: '/lab/$runId'
      path: '/lab/$runId'
      fullPath: '/lab/$runId'
      preLoaderRoute: typeof LabRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genome/$runId': {
      id: '/genome/$runId'
      path: '/genome/$runId'
      fullPath: '/genome/$runId'
      preLoaderRoute: typeof GenomeRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin/$runId': {
      id: '/digital-twin/$runId'
      path: '/digital-twin/$runId'
      fullPath: '/digital-twin/$runId'
      preLoaderRoute: typeof DigitalTwinRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  DigitalTwinRunIdRoute: DigitalTwinRunIdRoute,
  GenomeRunIdRoute: GenomeRunIdRoute,
  LabRunIdRoute: LabRunIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
